package com.procesosguardianes.generacioncalendario;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Calendar implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Calendar() {
    }




}