package com.procesosguardianes.generacioncalendario;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DayConfiguration implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DayConfiguration() {
    }




}